version: '3'
services:
  concourse:
    build: .
    command: ./concourse serve
    ports:
      - 8083:8083
    environment:
      HTTP_SERVER_HOST: ""
      HTTP_SERVER_PORT: 8083
    container_name: concourse
