version: '3'
services:
  concourse:
    build: .
    command: ./concourse serve
    ports:
      - 8084:8084
    environment:
      HTTP_SERVER_HOST: ""
      HTTP_SERVER_PORT: 8084
    container_name: concourse
